container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build (gcc)
      install_dependencies_script:
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      debug_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      release_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      release_shared_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
      container:
        matrix:
          - image: gcc:11
          - image: gcc:10
          - image: gcc:9
          - image: gcc:8
          - image: gcc:7
          - image: gcc:6
          - image: gcc:5
          - image: gcc:4.9
    - name: Build (clang)
      install_dependencies_script:
        - apt-get update
        - wget https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.sh -qO cmake.sh && sh cmake.sh --skip-license --prefix=/usr
      debug_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      release_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      release_shared_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      container:
        matrix:
          - image: silkeh/clang:11
          - image: silkeh/clang:10
          - image: silkeh/clang:9
          - image: silkeh/clang:8
          - image: silkeh/clang:7
          - image: silkeh/clang:6
          - image: silkeh/clang:5
          - image: silkeh/clang:4
    - name: Build (gcc)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y cmake gcc g++
      debug_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      release_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      release_shared_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
      debug_asan_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASanDebug -DENABLE_UBSAN=ON
      debug_tsan_script: TIMEOUT=2400 LOOP_COUNT=1000000 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSanDebug
      release_asan_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASan -DENABLE_UBSAN=ON
      release_tsan_script: TIMEOUT=2400 LOOP_COUNT=1000000 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSan
      container:
        matrix:
          - image: ubuntu:20.04
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on FreeBSD
      install_dependencies_script:
        - pkg install -y bash gmake cmake git
      debug_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release
      release_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Debug
      release_shared_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
      debug_asan_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASanDebug -DENABLE_UBSAN=ON
      debug_tsan_script: TIMEOUT=2400 LOOP_COUNT=1000000 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSanDebug
      release_asan_script: ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=ASan -DENABLE_UBSAN=ON
      release_tsan_script: TIMEOUT=2400 LOOP_COUNT=1000000 ./ci/run_tests.sh -DCMAKE_BUILD_TYPE=TSan
      freebsd_instance:
        matrix:
          #- image: freebsd-12-1-release-amd64
          - image: freebsd-11-4-release-amd64
